const mangas = [
    {
        "id":200001,
        "titulo": "Oshi no ko - new idol",
        "vol": "1",
        "desc":"Es un manga que narra la historia de Gorou, un médico que reencarna como el hijo de su ídolo, la estrella del pop Ai Hoshino. Renacido",
        "image":"../asset/img/Productos/Superman-Tomo1.jpg",
        "price":"15000",
        "stock":"10",
        "editorial":"Polis Metro",
    },
    {
        "id":200002,
        "titulo": "shuumatsu no valkyrie",
        "vol": "1",
        "desc":"Es un manga sobre un torneo épico donde 13 dioses se enfrentan a 13 héroes humanos para decidir el destino de la humanidad...",
        "image":"../asset/img/Mangas/Shuumatsu-portada.jpg",
        "price":"30000",
        "stock":"15",
        "editorial":"Shueisha ",
    },
    {
        "id":200003,
        "titulo": "Boku no Kokoro no Yabai Yatsu",
        "vol": "1",
        "desc":"Es un manga que sigue a Ichikawa Kyotaro, un estudiante de secundaria introvertido con pensamientos oscuros y...",
        "image":"../asset/img/Mangas/Boku-no-kokoro-Portada.jpg",
        "price":"25000",
        "stock":"8",
        "editorial":"Akita Shoten",
    },
    {
        "id":200004,
        "titulo": "Digimon adventure ZT",
        "vol": "1",
        "desc":"Es una secuela de la serie original Digimon Adventure que sigue a un nuevo grupo de niños elegidos, incluidos Daisuke, Hikari y Takeru...",
        "image":"../asset/img/Mangas/Digimn-Portada.jpg",
        "price":"12000",
        "stock":"14",
        "editorial":"Toei Animation",
    },
    {
        "id":200005,
        "titulo": "Nanatsu No Taizai",
        "vol": "1",
        "desc":"Es un manga y anime sobre un grupo de caballeros deshonrados llamados Los Siete Pecados Capitales, liderados por Meliodas. Conocidos...",
        "image":"../asset/img/Mangas/Nanatsu-Portada.jpg",
        "price":"20000",
        "stock":"7",
        "editorial":"Kōdansha",
    },
    {
        "id":200006,
        "titulo": "Four knight of the Apocalypse",
        "vol": "1",
        "desc":"Es una secuela de Nanatsu no Taizai que sigue a Tristan Liones, el hijo de Meliodas y Elizabeth, quien hereda los poderes de sus padres...",
        "image":"../asset/img/Mangas/Four-Knight-Portada.jpg",
        "price":"25000",
        "stock":"14",
        "editorial":"Norma Editorial",
    },
    {
        "id":200007,
        "titulo": "Mobile Suit Gundam 00",
        "vol": "1",
        "desc":"Es una serie ambientada en un futuro donde la humanidad depende de ascensores espaciales para obtener energía solar. Un...",
        "image":"../asset/img/Mangas/Gundam-portada-jpg.jpg",
        "price":"10000",
        "stock":"6",
        "editorial":"BEC",
    },
    {
        "id":200008,
        "titulo": "One Punch Man - Saitama",
        "vol": "1",
        "desc":"Es una serie sobre Saitama, un hombre aparentemente común que se convierte en superhéroe después de entrenar intensamente...",
        "image":"../asset/img/Mangas/One-punch.jpg",
        "price":"25000",
        "stock":"5",
        "editorial":"Shūeisha",
    },
    {
        "id":200009,
        "titulo": "The Jack the Ripper Case Files",
        "vol": "1",
        "desc":"Es un manga que narra la historia de Gorou, un médico que reencarna como el hijo de su ídolo, la estrella del pop Ai Hoshino. Renacido",
        "image":"../asset/img/Mangas/jack-The-Ripper-Portada.jpg",
        "price":"15990",
        "stock":"21",
        "editorial":"George G. Harrap & Co Ltd,",
    },
    {
        "id":200010,
        "titulo": "Fate: Grand Order",
        "vol": "1",
        "desc":"Es un manga y serie de la franquicia Fate donde los jugadores son Maestros que viajan a través del tiempo para corregir anomalías históricas...",
        "image":"../asset/img/Mangas/Fate-Grand-order-portada.jpg",
        "price":"10000",
        "stock":"5",
        "editorial":"Lerche",
    },
    {
        "id":200011,
        "titulo": "High school DXD - Hero",
        "vol": "1",
        "desc":"Sigue a Issei Hyoudou, un estudiante de secundaria pervertido que es asesinado en su primera cita y resucitado como demonio por Rias Gremory, una...",
        "image":"../asset/img/Mangas/High School DxD-Portada.jpg",
        "price":"30000",
        "stock":"3",
        "editorial":"Fujimi Shobo",
    },
    {
        "id":200012,
        "titulo": "High School Of The Dead",
        "vol": "1",
        "desc":"sigue a un grupo de estudiantes de secundaria que luchan por sobrevivir tras un apocalipsis zombi. Liderados por Takashi Komuro, el grupo, junto...",
        "image":"../asset/img/Mangas/High-of-the-dead.jpg",
        "price":"17000",
        "stock":"9",
        "editorial":"Fujimi Shobo",
    },
];

module.exports = {
    mangas
}